
language: ruby
rvm: 2.5.1
env: 
  - RAILS_ENV=test
before_script:
  - "postgresql -e 'create database api_test;'"
  - "cp ./.travis.database.yml ./config/database.yml"
script: 
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake spec